---
- name: Ensure namespace exists
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ selenium_grid_project_name }}'
        annotations:
          openshift.io/display-name: '{{ selenium_grid_project_display }}'
      spec: {}

- name: Wait for selenium-grid-operator package manifest to be available
  k8s_info:
    api_version: packages.operators.coreos.com/v1
    kind: PackageManifest
    namespace: openshift-marketplace
    name: selenium-grid-operator
  register: selenium_grid_package_manifest
  until: selenium_grid_package_manifest.resources|length > 0 and (selenium_grid_package_manifest.resources|first).status.catalogSource == "redhatgov-operators"
  retries: 5
  delay: 10

- name: Subscribe to Selenium Grid
  k8s:
    definition: '{{ lookup("template", "selenium-grid-subscription.yml.j2")|from_yaml }}'

- name: Create SeleniumGrid from a CR
  k8s:
    namespace: '{{ selenium_grid_project_name }}'
    definition:
      apiVersion: redhatgov.io/v1alpha1
      kind: SeleniumGrid
      metadata:
        name: selenium-grid
      spec:
        expose:
          kind: None
  register: selenium_grid_deployment
  until: not selenium_grid_deployment.failed
  retries: 5
  delay: 10
