---
- name: Check pipeline service account for user {{ username }}
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ username }}-cicd'
    api_version: v1
    kind: ServiceAccount
    name: pipeline
  register: pipeline_sa

- name: Add registry.redhat.io secret to pipeline service account for user {{ username }}
  k8s_json_patch:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ username }}-cicd'
    kind: ServiceAccount
    name: pipeline
    patch:
      - op: add
        path: /secrets/-
        value: { name: 'registry-rhio-pull-secret' }
  when: '"registry-rhio-pull-secret" not in pipeline_sa.resources[0].secrets | map(attribute="name") | list'

- name: Add quay secret to pipeline service account for user {{ username }}
  k8s_json_patch:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ username }}-cicd'
    kind: ServiceAccount
    name: pipeline
    patch:
      - op: add
        path: /secrets/-
        value: { name: 'quay-reg-pull-secret' }
  when: '"quay-reg-pull-secret" not in pipeline_sa.resources[0].secrets | map(attribute="name") | list'
