---
- name: Get a fresh CodeReady SSO admin token
  uri:
    url: '{{ keycloak_url }}/auth/realms/master/protocol/openid-connect/token'
    validate_certs: false
    method: POST
    body:
      username: "{{ sso_admin_user }}"
      password: "{{ sso_admin_password }}"
      grant_type: "password"
      client_id: "admin-cli"
    body_format: form-urlencoded
    status_code: 200,201,204
  register: codeready_sso_admin_token

- import_tasks: create_crw_user.yml
- import_tasks: create_crw_workspace.yml
- import_tasks: verify_crw_workspace.yml
