---
- name: "Get Che {{ user.username }} token"
  uri:
    url: "{{ keycloak_url }}/auth/realms/codeready/protocol/openid-connect/token"
    validate_certs: false
    method: POST
    body:
      username: "{{ user.username }}"
      password: "{{ user.password }}"
      grant_type: "password"
      client_id: "codeready-public"
    body_format: form-urlencoded
    status_code: 200
  register: user_token
  until: not user_token.failed

- name: Get workspace for {{ user.username }}
  uri:
    url: 'https://{{ codeready_route }}/api/workspace'
    validate_certs: false
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200
  register: workspace_def
  until: not workspace_def.failed

- name: Verify and start workspace for {{ user.username }} again if stopped
  when: workspace_def.json[0].status == "STOPPED"
  uri:
    url: 'https://{{ codeready_route }}/api/workspace/{{ workspace_def.json[0].id }}/runtime'
    validate_certs: false
    method: POST
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200
  register: workspace_start
  ignore_errors: yes

- name: Notify of soft failures
  debug:
    msg: >-
      Unable to start the workspace. CRW for {{ user.username }} may not be
      fully hotloaded, but this failure shouldn't be catastrophic.
  when:
  - workspace_start.failed is defined
  - workspace_start.failed|bool
