- name: Get Mattermost URL
  community.kubernetes.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ mattermost_name }}-mattermost"
    namespace: "{{ mattermost_namespace }}"
  register: mattermost_route
  retries: 10
  delay: 3
  until: mattermost_route.resources[0].spec.host is defined

- name: Set mattermost_url Variable
  set_fact:
    mattermost_url: "{{ mattermost_route.resources[0].spec.host }}"

- name: Create KeyCloak Client
  community.kubernetes.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'mattermost-keycloak-client.yml.j2') }}"

# TODO: this logic assumes no existing attributes, which might be overwritten by this
- name: Patch KeyCloak Users to Have mattermostId Attribute
  community.kubernetes.k8s:
    state: present
    definition: |-
      apiVersion: keycloak.org/v1alpha1
      kind: KeycloakUser
      metadata:
        name: "{{ item.username }}"
        namespace: "{{ rhsso_project_name }}"
      spec:
        user:
          attributes:
            mattermostId:
            - "{{ index }}"
  loop: "{{ rhsso_users }}"
  loop_control:
    index_var: index
