---
deploy_quay: true
deploy_gitea: true
deploy_argocd: true
deploy_sonarqube: true
deploy_nexus: true
deploy_crw: true
deploy_selenium_grid: true
deploy_mattermost_operator: true

subdomain: '{{ full_cluster_name }}'

redhat_gov_catalog_tag: "latest"

jenkins_repository_name: openshift-release-dev

crw_admin_user:
  username: codeready-admin
  password: demo123

operator_list:
- rhsso
- gitea
- argocd
- sonarqube
- mattermost
- crw
- selenium_grid

