---
- name: Make an API request for each user to migrate this project
  uri:
    url: https://gitea-server-{{ gitea_project_name }}.{{ cluster_router }}/api/v1/repos/migrate
    validate_certs: no
    body_format: json
    method: POST
    headers:
      Authorization: token {{ user.token }}
    body: |
      {
        "clone_addr": "https://github.com/{{ tasks_github_project }}/{{ repo }}.git",
        "uid": {{ user.uid|int }},
        "repo_name": "openshift-tasks"
      }
  register: gitea_repo_migration_task
  failed_when: gitea_repo_migration_task.status != 201
  loop: '{{ gitea_user_tokens }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'
