galaxy_info:
  author: Griffin College
  description: A role to install mattermost on OpenShift. Currently this role only supports deployment via a Red Hat written mattermost operator.
  company: Red Hat

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []
