---
workshop_spawner_project_name: devsecops
workshop_spawner_project_display: DevSecOps Common Resources

workshop_spawner_image: quay.io/redhatgov/workshop-spawner:latest
workshop_dashboard_image: quay.io/redhatgov/devsecops-workshop-dashboard:{{ pipeline_style|default("tekton") }}

crw_project_name: devsecops
rocketchat_project_name: devsecops

keycloak_url: "https://keycloak-{{ crw_project_name }}.{{ cluster_router }}"
spawner_redirect_uri: "https://dashboard.{{ cluster_router }}/hub/oauth_callback"
