---
- name: Ensure namespace exists
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ sonarqube_project_name }}'
        annotations:
          openshift.io/display-name: '{{ sonarqube_project_display }}'
      spec: {}

- name: Wait for sonarqube-operator package manifest to be available
  k8s_info:
    api_version: packages.operators.coreos.com/v1
    kind: PackageManifest
    namespace: openshift-marketplace
    name: sonarqube-operator
  register: sonarqube_package_manifest
  until: sonarqube_package_manifest.resources|length > 0 and (sonarqube_package_manifest.resources|first).status.catalogSource == "redhatgov-operators"
  retries: 5
  delay: 10

- name: Get a list of operator groups
  k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: '{{ sonarqube_project_name }}'
  register: operator_groups

- set_fact:
    operator_group_name: '{{ operator_groups.resources[0].metadata.name }}'
  when: operator_groups.resources

- name: Subscribe to sonarqube
  k8s:
    definition: '{{ lookup("template", "sonarqube-subscription.yml.j2")|from_yaml }}'

- name: Create SonarQube from a CR
  k8s:
    namespace: '{{ sonarqube_project_name }}'
    definition:
      apiVersion: redhatgov.io/v1alpha1
      kind: Sonarqube
      metadata:
        name: sonarqube
      spec:
        persistent: true
        postgresql:
          volumeSize: 4Gi
        sonarqube:
          expose:
            kind: Route
            ssl: true
            uri: sonarqube-{{ sonarqube_project_name }}.apps.{{ cluster_name }}.{{ openshift_base_domain }}
          volumeSize: 4Gi
  register: sq_deployment
  until: not sq_deployment.failed
  retries: 5
  delay: 10

- name: Wait for SonarQube route to be created by the Operator
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: '{{ sonarqube_project_name }}'
    name: sonarqube
  register: sonarqube_route
  until:
    - sonarqube_route.resources is defined
    - sonarqube_route.resources|length > 0
  retries: 10
  delay: 30

- name: Wait for SonarQube route to begin answering requests
  uri:
    url: 'https://{{ sonarqube_route|json_query("resources[0].spec.host") }}/'
    return_content: yes
    validate_certs: no
  register: sonarqube_index
  until: '"doctype html" in sonarqube_index.content'
  retries: 10
  delay: 30

- name: Retrieve SonarQube pod info (for name)
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ sonarqube_project_name }}'
    label_selectors:
      - app = sonarqube
  register: sonarqube_pod
  until: sonarqube_pod.resources|length > 0
  retries: 10
  delay: 30

# There's no current way to get logs from Ansible natively, track issue:
# https://github.com/ansible/ansible/issues/67898
# For now, using oc
- name: Wait for SonarQube to report up
  shell: |
    oc='{{ oc_cli }}'
    admin_user='{{ workshop_admin.username }}'
    admin_password='{{ workshop_admin.password }}'
    if [ $($oc whoami) != "$admin_user" ]; then
        $oc login --insecure-skip-tls-verify=true -u "$admin_user" -p "$admin_password" && echo changed || echo failed
    else
        echo ok
    fi
    timeout={{ pod_timeout }}
    delay={{ pod_delay }}
    wait=0
    while ! $oc logs -n {{ sonarqube_project_name }} {{ (sonarqube_pod.resources|first).metadata.name }} | grep -qF 'SonarQube is up'; do
        sleep $delay
        (( wait += delay ))
        [ $wait -ge $timeout ] && exit 1 ||:
    done
  changed_when: false
  vars:
    pod_delay: 10
    pod_timeout: 600

- name: Configure SonarQube and RHSSO to work together
  include: sonarqube_rhsso.yml
