---
- name: Ensure namespace exists
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ nexus_project_name }}'
        annotations:
          openshift.io/display-name: '{{ nexus_project_display }}'
      spec: {}

- name: Wait for nexus-operator package manifest to be available
  k8s_info:
    api_version: packages.operators.coreos.com/v1
    kind: PackageManifest
    namespace: openshift-marketplace
    name: nexus-operator
  register: nexus_package_manifest
  until: nexus_package_manifest.resources|length > 0 and (nexus_package_manifest.resources|first).status.catalogSource == "redhatgov-operators"
  retries: 5
  delay: 10

- name: Subscribe to Nexus
  k8s:
    definition: '{{ lookup("template", "nexus.yml.j2")|from_yaml }}'

- name: Deploy Nexus via CR
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition:
      apiVersion: redhatgov.io/v1alpha1
      kind: Nexus
      metadata:
        name: nexus
      spec:
        persistent: true
        nexus:
          allowAnonymousAccess: true
          oauth:
            enabled: true
            adminUsers: '{{ nexus_oauth_admin_users | default([]) }}'
            bypassAuthFor: '{{ nexus_oauth_bypass_paths | default([]) }}'
          expose:
            ssl: true
            kind: Route
          image:
            src: registry.connect.redhat.com/sonatype/nexus-repository-manager
            tag: latest
            pullPolicy: IfNotPresent
          volumeSize: 10Gi
  register: nexus_deployment
  until: not nexus_deployment.failed
  retries: 5
  delay: 10

- name: Wait for Nexus to finish being created
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ nexus_project_name }}'
    label_selectors:
      - app=nexus
  register: nexus_pod
  until: nexus_pod.resources|length > 0 and (nexus_pod.resources|first).status.phase == "Running"
  retries: 10
  delay: 30

- name: Add NexusUsers to create local rut-auth accounts
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition: '{{ lookup("template", "nexususer.yml.j2")|from_yaml }}'
