---

- name: Wait for Nexus route to be created by the Operator
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: '{{ nexus_project_name }}'
    name: nexus
  register: nexus_route
  until: nexus_route.resources|length > 0
  retries: 10
  delay: 30

- name: Wait for Nexus route to begin answering requests
  uri:
    url: 'http://{{ nexus_route|json_query("resources[0].spec.host") }}/'
    return_content: yes
    validate_certs: no
  register: nexus_index
  until: '"DOCTYPE html" in nexus_index.content'
  retries: 10
  delay: 30

- name: Retrieve admin password for Nexus
  shell: |
    oc='{{ oc_cli }}'
    admin_user='{{ workshop_admin.username }}'
    admin_password='{{ workshop_admin.password }}'
    if [ $($oc whoami) != "$admin_user" ]; then
        $oc login --insecure-skip-tls-verify=true -u "$admin_user" -p "$admin_password" &>/dev/null || exit 1
    fi

    counter=0
    pod=$($oc get pods -n {{ nexus_project_name }} -l app=nexus -o jsonpath='{.items[0].metadata.name}')
    while ! $oc exec $pod -n {{ nexus_project_name }} -- [ -f /nexus-data/admin.password ] &>/dev/null; do
        sleep 1
        ((counter++))
        [ $counter -gt 300 ] && exit 1
    done
    $oc exec $pod -n {{ nexus_project_name }} -- cat /nexus-data/admin.password || exit 1
  register: nexus_password
  changed_when: false

- name: Add deployment user to Nexus instance
  shell: >-
    devsecops-api nexus add-user
    http://{{ nexus_route|json_query("resources[0].spec.host") }}
    --login-username admin --login-password '{{ nexus_password.stdout }}'
    --usernames 'deployment'
    --passwords 'deployment123'
  register: deployment_user
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: deployment_user.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: deployment_user.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or deployment_user.rc != 0

- name: Add users to Nexus instance
  shell: >-
    devsecops-api nexus add-user
    http://{{ nexus_route|json_query("resources[0].spec.host") }}
    --login-username admin --login-password '{{ nexus_password.stdout }}'
    --usernames '{{ workshop_users|json_query("[].username")|join(",") }}'
    --passwords '{{ workshop_users|json_query("[].password")|join(",") }}'
  register: nexus_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: nexus_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: nexus_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or nexus_users.rc != 0

- name: Create a new repository named after every user
  shell: >-
    devsecops-api nexus add-repository
    http://{{ nexus_route|json_query("resources[0].spec.host") }}
    --login-username admin --login-password '{{ nexus_password.stdout }}'
    --repository-names '{{ workshop_users|json_query("[].username")|join(",") }}'
  register: nexus_repos
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or nexus_repos.rc != 0

- name: Create a new proxy repository for redhat-ga
  shell: >-
    devsecops-api nexus add-proxy-repository
    http://{{ nexus_route|json_query("resources[0].spec.host") }}
    --login-username admin --login-password '{{ nexus_password.stdout }}'
    --repository-name 'redhat-ga-proxy'
    --remote-repo-url 'https://maven.repository.redhat.com/ga/'
  register: redhat_ga_proxy
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: redhat_ga_proxy.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: redhat_ga_proxy.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or redhat_ga_proxy.rc != 0

- name: Update maven-public repo with redhat-ga proxy repo
  shell: >-
    devsecops-api nexus update-group-repo
    http://{{ nexus_route|json_query("resources[0].spec.host") }}
    --login-username admin --login-password '{{ nexus_password.stdout }}'
    --group-repository-name 'maven-public'
    --member-repository-names 'maven-releases,maven-snapshots,maven-central,redhat-ga-proxy'
  register: maven_public_repo
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: maven_public_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: maven_public_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or maven_public_repo.rc != 0
