- name: Create Username Distribution Deployment
  k8s:
    namespace: '{{ username_distribution_project_name }}'
    definition: "{{ lookup('template', 'username-distribution.yml.j2')|from_yaml }}"

- name: Wait for Username Distribution to finish being created
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ username_distribution_project_name }}'
    label_selectors:
      - app=username-distribution
  register: distro_pod
  until: distro_pod.resources|length > 0 and (distro_pod.resources|first).status.phase == "Running"
  retries: 10
  delay: 30
