---
- hosts: localhost
  tasks:
    - name: Get cluster dns
      k8s_info:
        api_version: config.openshift.io/v1
        kind: DNS
        namespace: openshift-config
        name: cluster
      register: cluster_dns

    - set_fact:
        cluster_name: '{{ (cluster_dns.resources|first).spec.baseDomain.split(".")[0] }}'

    - set_fact:
        openshift_base_domain: "{{ (cluster_dns.resources|first).spec.baseDomain.replace(cluster_name + '.','') }}"
        tssc_namespace: "{{ ansible_operator_meta.namespace }}"
        rhedsord_registry_username: TODO
        rhedsord_registry_password: TODO

    - name: Set project names
      set_fact:
        argocd_project_name: '{{ tssc_namespace }}'
        crw_project_name: '{{ tssc_namespace }}'
        crw_deployment_type: tssc
        gitea_project_name: '{{ tssc_namespace }}'
        jenkins_project_name: '{{ tssc_namespace }}'
        mattermost_namespace: '{{ tssc_namespace }}'
        nexus_project_name: '{{ tssc_namespace }}'
        quay_project_name: '{{ tssc_namespace }}'
        rhsso_project_name: '{{ tssc_namespace }}'
        selenium_grid_project_name: '{{ tssc_namespace }}'
        sonarqube_project_name: '{{ tssc_namespace }}'

    - name: Set tssc service account secret
      set_fact:
        tssc_service_account_secret: tssc-service-account-credentials

    - name: Look for default defined common variables
      include_vars: ../vars/tssc-platform/common.yml
      when: common_included is not defined or not common_included

    - fail:
        msg: Unable to continue without common variables set
      when: common_included is not defined or not common_included

    - name: Look for default defined rhedsord variables
      include_vars: ../vars/tssc-platform/rhedsord.yml
      when: rhedsord_included is not defined or not rhedsord_included

    - fail:
        msg: Unable to continue without rhedsord variables set
      when: rhedsord_included is not defined or not rhedsord_included

    - include_role:
        name: tssc-platform/deployment
      when: cr_type == 'platform'

    - include_role:
        name: tssc-pipeline
      when: cr_type == 'pipeline'

    - include_tasks: cleanup-tssc-platform.yml
      when: cr_state == 'absent'
