---
mattermost_name: mattermost
mattermost_namespace: devsecops
mattermost_operator_channel: stable

database:
  drivername: postgres
  name: mattermost
  password: mattermost
  port: 5432

subdomain: '{{ full_cluster_name }}'
