---
- name: Generate projects per-user
  k8s:
    definition: '{{ lookup("template", "project.yml.j2")|from_yaml }}'

- include_role:
    name: common/redhatgov-catalog

- name: Get a list of operator groups
  k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: '{{ tssc_namespace }}'
  register: operator_groups

- set_fact:
    operator_group_name: '{{ operator_groups.resources[0].metadata.name }}'
  when: operator_groups.resources

- name: Ensure OperatorGroup exists
  k8s:
    definition: '{{ lookup("template", "operator-group.yml.j2") }}'

- name: 'Create Subscription for {{ item }}'
  k8s:
    definition: '{{ lookup("template", "subscriptions/" + item + ".yml.j2") }}'
  loop: '{{ operator_list }}'

- name: 'Create CustomResource for {{ item }}'
  k8s:
    definition: '{{ lookup("template", "custom-resources/" + item + ".yml.j2") }}'
  register: deployment
  until: not deployment.failed
  retries: 5
  delay: 10
  loop: '{{ operator_list }}'

- include_role:
    name: devsecops-workshop/quay
  when: deploy_quay
- include_role:
    name: devsecops-workshop/gitea
  when: deploy_gitea
- include_role:
    name: devsecops-workshop/sonarqube
  when: deploy_sonarqube
- include_role:
    name: devsecops-workshop/nexus
  when: deploy_nexus
- include_role:
    name: common/codeready-workspaces
  when: deploy_crw
- include_role:
    name: devsecops-workshop/username-distribution
  when: deploy_username_distribution
- include_role:
    name: devsecops-workshop/rocket-chat
  when: deploy_rocketchat
- include_role:
    name: devsecops-workshop/workshop-spawner
  when: deploy_workshop

- include_role:
    name: devsecops-workshop/tekton
  when:
    - deploy_pipeline
    - pipeline_style == 'tekton'
- include_role:
    name: devsecops-workshop/tekton-pipeline
  when:
    - deploy_pipeline
    - pipeline_style == 'tekton'

- include_role:
    name: devsecops-workshop/jenkins
  when:
    - deploy_pipeline
    - pipeline_style == 'jenkins'
